### ISSUE TITLE
Touch Controller Issues

### ISSUE THREAD

**Issue by thomasjeffreyandersontwin** [polygraphene/ALVR#484] opened 2019-07-30 02:50 UTC
Oculus quest  controller triggers don't have any response in the STEAMVR menu nor the game. Also only one controller is active at a time. If i click a button on one controller the other freezes, ie is non responsive.

**Comment by krzys-h** [comment] 2019-07-30 07:08
Recent firmware update on Quest broke it, duplicate of #479, #477, #476, #483, see polygraphene/ALVRClient#32 for the fix

**Comment by nk33** [comment] 2019-08-03 10:51
Hi Guys - I have this issue with my controllers on my Quest - it can only see one at a time....

i used to be able to play all pc vr games no problem.

problem is i am not a developer so dont know how to fix this....is there a guide somewhere? 

is there also a way to turn off auto update on the quest?

**Comment by dudecatbobe** [comment] 2019-08-03 19:44
I have the same problem as nk33, I can only see one controller at a time and on is just floating in my face

**Comment by krzys-h** [comment] 2019-08-03 21:45
See https://github.com/polygraphene/ALVR/issues/491

**Comment by nk33** [comment] 2019-08-04 11:56
its ok - i found a link to a patched one

https://drive.google.com/file/d/1-YHOu1w6CmhGj9UnoSAJahqIrGOvXSUx/view

**Closed** 2021-11-08 10:53 UTC
