### ISSUE TITLE
Alvr client Error with pics (please help)

### ISSUE THREAD

**Issue by ICURSEDANGEL** [polygraphene/ALVR#89] opened 2018-06-23 22:08 UTC
my pc is 64 bit and theres a proof pic. (Nothing works even if i click disconnect or start server same error shows up what do i do)

![screenshot_3](https://user-images.githubusercontent.com/40498348/41814035-ee8a97a2-774a-11e8-9e7c-1a1897bdc037.png)

![screenshot_1](https://user-images.githubusercontent.com/40498348/41814002-5921378e-774a-11e8-9390-b98b7e44676e.png)

![screenshot_2](https://user-images.githubusercontent.com/40498348/41814003-5a518ee2-774a-11e8-910e-af75384bff34.png)

**Comment by thoughtfix** [comment] 2018-06-23 22:14
Did you make sure the 64bit version of the Visual C runtime is installed? The link in the instruction page has both.

**Comment by Muhlawor** [comment] 2018-06-23 22:14
Do you have steamvr installed?

**Comment by thoughtfix** [comment] 2018-06-23 22:16
Also I see your system is a 4200U with 4 GB RAM.  ALVR requires a SteamVR capable system to run.  Run this and see if you can even run SteamVR: https://store.steampowered.com/app/323910/SteamVR_Performance_Test/

**Comment by ICURSEDANGEL** [comment] 2018-06-23 22:20
@thoughtfix yes i do have it installed 2017 both 64 and 32 bit versions installed and the pc runs some steamvr games i tried with trinus vr and it worked.

**Comment by ICURSEDANGEL** [comment] 2018-06-23 22:20
@Muhlawor yes it is installed and up to date

**Comment by ICURSEDANGEL** [comment] 2018-06-23 22:37
@thoughtfix it says:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Exception of type 'System.Exception' was thrown.
   at ALVR.SoundDevice.GetSoundDeviceList()
   at ALVR.Launcher.Launcher_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at MetroFramework.Forms.MetroForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at MetroFramework.Forms.MetroForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2671.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ALVR
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/justk/Desktop/ALVR/ALVR.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MetroFramework
    Assembly Version: 1.2.0.3
    Win32 Version: 1.2.0.3
    CodeBase: file:///C:/Users/justk/Desktop/ALVR/MetroFramework.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2661.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MetroFramework.Fonts
    Assembly Version: 1.2.0.3
    Win32 Version: 1.2.0.3
    CodeBase: file:///C:/Users/justk/Desktop/ALVR/MetroFramework.Fonts.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ICURSEDANGEL** [comment] 2018-06-23 22:38
@thoughtfix what do i do?

**Comment by thoughtfix** [comment] 2018-06-23 22:53
I don't develop for this project - I was just trying to help. I think you might be wasting your time based on your system specs, however. Follow along the "new user - help" thread in #86 and see if there's any good advice for you in there and good luck!

**Comment by vrokolos** [comment] 2018-06-23 22:57
What GPU do you have?

**Comment by ICURSEDANGEL** [comment] 2018-06-23 23:11
@vrokolos AMD Radeon HD 8670M it might not be compatible but it does run some steam vr games good

**Comment by vrokolos** [comment] 2018-06-23 23:21
No that doesn't work. ALVR uses nvidias NVENC encoder to stream games. This means only newer nvidia cards work. AMD won't work with this.

**Comment by ICURSEDANGEL** [comment] 2018-06-23 23:32
@vrokolos but its a .net error doesnt say anything about graphics card

**Comment by vrokolos** [comment] 2018-06-23 23:36
It is trying to load nvidias driver and it can't find it so you're out of luck

**Comment by Muhlawor** [comment] 2018-06-23 23:37
Whatever, it will not work with AMD.

**Comment by ICURSEDANGEL** [comment] 2018-06-23 23:46
@Muhlawor @vrokolos so if i use a computer with an nvidea graphics will it work?

**Comment by thoughtfix** [comment] 2018-06-23 23:49
@ICURSEDANGEL  you can contribute to the crowdfunding of the AMD support here: https://www.bountysource.com/issues/59270271-will-we-get-an-amd-compatible-version-in-the-future

**Comment by vrokolos** [comment] 2018-06-23 23:49
You need a nvenc supported nvidia card. https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

**Comment by polygraphene** [comment] 2018-06-24 00:19
@ICURSEDANGEL As other people said, even if you solve this bug, you cannot use ALVR. Because ALVR uses NVIDIA specific function. Sorry.

**Comment by ICURSEDANGEL** [comment] 2018-06-24 01:28
@polygraphene yes i got that but i atleast want to solve this ".NET" error so if it comes to me when i get my upgraded pc i could solve it immediatly.

**Comment by polygraphene** [comment] 2018-06-24 01:53
I think this error is caused by missing nvidia driver. Becasue ALVR driver depends on dll which is installed by nvidia driver.
If you get NVIDIA GPU and install graphic driver, this error may disappear.

**Comment by thoughtfix** [comment] 2018-06-24 19:18
@ICURSEDANGEL  please close this as a duplicate of #33 and subscribe to that one. You'll get an email from github if that issue is updated with AMD support.

**Closed** 2018-06-24 19:39 UTC
