### ISSUE TITLE
Controllers not working with Vivecraft

### ISSUE THREAD

**Issue by HanzoFactory** [polygraphene/ALVR#483] opened 2019-07-29 01:27 UTC
My controllers don't work with Vivecraft (just don't function at all, hands are reached in front and to the front direction of headset), but work perfectly fine with every other SteamVR game I've tried.

I tried getting help on their Discord server but in the end they couldn't manage to help me and said that the issue isn't on their part, and is with ALVR, so here I am.
From what I understand from the Vivecraft logs they just say "unknown issue" as the reason the controllers don't work.

Help would be much appreciated, thanks!

**Comment by krzys-h** [comment] 2019-07-30 07:07
Recent firmware update on Quest broke it, duplicate of #479, #477, #476, see polygraphene/ALVRClient#32 for the fix

**Comment by HanzoFactory** [comment] 2019-07-30 12:09
I'm not sure if you properly read my post, but I mentioned Vivecraft is the only game not working. Every other streamed game and ALVR itself works perfectly fine.

I contacted the Vivecraft devs about it and in the end they couldn't manage to help with it, and told me it's a problem with ALVR.

**Comment by Brichard0625** [comment] 2019-07-30 15:26
To the developers of ALVR due to a recent update, you have to include this line in your manifest.
<uses-feature android:name="android.hardware.vr.headtracking" android:required="true" android:version="1" />

I had the same issue when developing for the quest using unity.  Until this is added there will be no functionality with controllers and you will notice only one controller works at a time because it thinks your building for the GO/Gear VR.

**Comment by krzys-h** [comment] 2019-07-30 15:52
@HanzoFactory if it works in other games, it may be another issue - I just assumed that recent controller problems are likely that and didn't pay enough attention to the post, sorry ;)

**Comment by jrbudda** [comment] 2019-08-01 17:40
For anyone finding this thread. The newer versions of Vivecraft exclusively use SteamVR Input for controller access. The fork of ALVR that fixes controllers after the firmware update only fixes them for legacy openvr interfaces. ALVR will need to update to support SteamVR Input. In the meantime you can use older versions of Vivecraft that use the legacy openvr system.

**Comment by SpookyBear0** [comment] 2019-10-01 01:05
what versions work?

**Comment by TheDaybroken** [comment] 2021-01-04 19:10
All you need to do is just change your mode from seated to standing, works on all versions and you don't need that openvr version garbage

**Closed** 2021-11-08 10:53 UTC
