### ISSUE TITLE
v2.2.1-alpha quirks

### ISSUE THREAD

**Issue by VRtinker** [polygraphene/ALVR#96] opened 2018-06-28 00:25 UTC
Hello,

I wanted to report a few things I noticed and ask for quick guidance!

I found that when copying  ALVRFreePIE.dll to C:\Program Files (x86)\FreePIE\plugins, the file NEEDS to be unblocked in its properties, otherwise Freepie will run as a process (it will show in Task Manager), but it will not draw any GUI (so it practically borks FreePie). Maybe there's a way to unblock it before packaging it or else it should be noted that this change in the properties needs to occur for anything to work!

I noticed the new "Launch only SteamVR without Steam", but for me, every single previous release has been already doing that, in fact, if anything I would have expected the opposite option "Launch Steam AS WELL". So now I'm not sure if what's been happening on my machine is in fact an anomalous behavior, or what?!

When starting the server (regardless of whether you select to start with or without Steam), if SteamVR crashes, or you X it out (quit), the process vrserver.exe doesn't get killed, leaving ALVR status to "Server is Alive", making it impossible to restart SteamVR from ALVR, unless you kill vrserver.exe manually. Restarting ALVR doesn't cure this, in fact it makes things even worse by showing that's "alive" and connected to the client (if you previously closed ALVR while being connected to the client) while the client is truly not receiving anything (as it displays the message to "click connect"). The server though thinks it's connected so you are forced to disconnect/reconnect the client manually.

Ideally, exiting ALVR should kill every and all SteamVR related process (especially if started by it in the first place) or at least not get in the way of SteamVR "quit routine". It was convenient though to be able to quit SteamVR and return the to the "Server is Down" status without needing any taskkill operations.

Lastly, as I already mentioned in #79, I was hoping to make the positional tracking generated by  PSMoveSteamVRBridge+PSMoveFreepieBridge work with ALVR. While I am pumped that you integrated FreePie into the project, I couldn't for the life of me figure out how to adapt the script provided in  PSMoveFreepieBridge to the new variables you created.

Here is the "original" script I'm trying to work with (which allows Riftcat to use the data in their stream):

def update():
	freeTrack.pitch = -freePieIO[0].pitch
	freeTrack.roll =  freePieIO[0].roll
	freeTrack.yaw = freePieIO[0].yaw
	
	#Multiply by 10 for SteamVR use
	freeTrack.x = (freePieIO[0].x * 10)
	freeTrack.y = (freePieIO[0].y * 10)
	freeTrack.z = (freePieIO[0].z * 10)

	
if starting:
	freePieIO[0].update += update

I "get" it should get mashed-up with the following, but not fully getting how:

global offset

if starting:
  offset = [0.0, 0.0, 0.0]

alvr.override_head_position = True

alvr.head_position[0] = alvr.input_head_position[0] + offset[0]
alvr.head_position[1] = alvr.input_head_position[1] + offset[1]
alvr.head_position[2] = alvr.input_head_position[2] + offset[2]

I only want to use the x.y.z from the "original" script (I'm using a ping pong ball lightbulb tracker, and obviously prefer to use the GearVR IMU for the head orientation), and I'm assuming that freePieIO[0].x=alvr.input_head_position[0] (are they the same?). So, yeah, I'm stumped!

Hope you will shine some wisdom this way!

ありがと

**Comment by Lightsteed** [comment] 2018-06-28 04:31
I can confirm the vrserver.exe not getting killed properly. this is a bad problem, something that plagues NOLO still. It gets annoying very quickly as you have to manually kill it in task manager before you can use steamVR again, even if using it with a vive.

**Comment by VRtinker** [comment] 2018-06-28 04:59
> I can confirm the vrserver.exe not getting killed properly. this is a bad problem, something that plagues NOLO still. It gets annoying very quickly as you have to manually kill it in task manager before you can use steamVR again, even if using it with a vive.

OUCH! I'm sure this is a regression though, not a new feature. Every other previous build was shutting down SteamVR properly. To mitigate this, we can probably create a .bat that kills everything, to be executed on disconnect (although then you break the autoconnect if you manually disconnect). I'm confident @polygraphene will sort things out (and hopefully, magically make the VirtualHMD ping pong ball positional tracking work!)

**Comment by polygraphene** [comment] 2018-06-28 07:18
Thank you for detailed report!

>NEEDS to be unblocked

We need proper installer. #74 will resolve it.

>"Launch only SteamVR without Steam" ... already doing that

Yes. I forgot to mention. Default behaviour was changed!
Previous version launch only SteamVR. And new version launch Steam and you can rollback behaviour by enabling that option.

As you said, we need more robust mechanisms to manage SteamVR lifecycle. We can put "kill steamvr" button to GUI, but it is not "clean" solution.
related: https://github.com/ValveSoftware/openvr/issues/473 https://github.com/ValveSoftware/openvr/issues/779

**Comment by polygraphene** [comment] 2018-06-28 07:29
@vrokolos You can use "DebugCaptureOutput" on debug tab. It create "capture.h264" (even when you use H265) file on driver folder. I think your issue is caused by jitter of network. The jitter cause client to drop frames. As we disscussed on #42, we need buffering mechanism on client side to reduce frame drop.

**Comment by vrokolos** [comment] 2018-06-28 07:31
Great. I just want to make sure it's client side. I'll test it out thanks

**Comment by polygraphene** [comment] 2018-06-28 07:38
@vrokolos The file is raw h265 stream. You can play with ffplay, or transcode it with ffmpeg.

**Comment by vrokolos** [comment] 2018-06-28 07:39
Yeah got it thanks

**Comment by vrokolos** [comment] 2018-06-28 07:43
@VRtinker I have an automated setup of tasker and eventghost that will wake up my pc and run alvr server and bigscreen whenever i run alvr client and will kill all vr services when i remove my gear vr. Can give you more info if you need it

**Comment by vrokolos** [comment] 2018-06-28 07:45
@polygraphene I noticed some client crashes also. Is there a crash log on the client or should I use adb to get it?

**Comment by polygraphene** [comment] 2018-06-28 07:56
@vrokolos  Client has no crash log. You need to use adb. Thank you as always!

@VRtinker @Lightsteed Oh! I missed the point. That was a bug of newer version. It will be fixed on next alpha release.

**Comment by polygraphene** [comment] 2018-06-28 08:00
I didn't try, but it should look something like the following.
```
alvr.override_head_position = True

alvr.head_position[0] = freePieIO[0].x * 10
alvr.head_position[1] = freePieIO[0].y * 10
alvr.head_position[2] = freePieIO[0].z * 10
```
alvr.head_position[0],[1],[2] mean x,y,z coordinate respectively.

**Comment by VRtinker** [comment] 2018-06-28 09:21
@vrokolos Thanks for your offer, though I already have a system in place. I use [Remote Launcher Free](https://play.google.com/store/apps/details?id=com.owtroid.remotelauncherfree) on the phone and its relative [server side applet](http://owtroid.com/remotelauncher/mediawiki/index.php?title=Remote_Launcher#Installing_Remote_Launcher). I then have a NFC tag configured to initiate the sequence and one to terminate it, so that I can just bang one of the controller to the phone to start everything and the other to kill everything. I use an NFC tag attached to a daydream controller to retool the Gear VR into a Daydream View (that's where I got the idea).

@polygraphene 
>alvr.override_head_position = True
>
>alvr.head_position[0] = freePieIO[0].x * 10
alvr.head_position[1] = freePieIO[0].y * 10
alvr.head_position[2] = freePieIO[0].z * 10


YAY! It works! except I had to change from *10 to /100, so here is how the script looks like now:

alvr.override_head_position = True

alvr.head_position[0] = freePieIO[0].x /100
alvr.head_position[1] = freePieIO[0].y /100
alvr.head_position[2] = freePieIO[0].z /100

It was just a cursory test but seems pretty spot on. As soon as I turn on the ping pong ball, it immediately tracks in space, and as I turn it off, it throws me right back in the initial position. When multiplying "*10" it would throw me up high, waaaaaay up high, so high you wouldn't even see the guidelines, just the default gray background. Using "/10" keeps me "grounded", but it's waaaaay too sensitive (heavy breathing would be enough to skew a few meters to the sides). "/100" felt about right, but maybe there's a way to calculate this number exactly instead of through guesstimation?!?

During the next 24hrs I will put the setup under a more proper stress test to see how it holds up.

Thanks a lot, again, for your outstanding work!

**Comment by polygraphene** [comment] 2018-06-28 10:13
Great!
SteamVR accepts coordinates in meters. Put alvr.head_position[*] in meters.
And Your PSMove may report in centi-meter.

**Comment by VRtinker** [comment] 2018-06-30 06:13
So I had a chance to test a little more and arrived to the conclusion that an offset needs to be added in the script in order to attempt proper positional tracking. By using the diagnostic.watch function I determined that y and z both need to be adjusted with an offset that should look like this: [0.0, 0.1, -0.1]. I tried to following:

global offset
if starting:
  offset = [0.0, 0.1, -0.1]

alvr.override_head_position = True

alvr.head_position[0] = alvr.input_head_position[0] + offset[0]
alvr.head_position[1] = alvr.input_head_position[1] + offset[1]
alvr.head_position[2] = alvr.input_head_position[2] + offset[2]
alvr.head_position[0] = freePieIO[0].x /100
alvr.head_position[1] = freePieIO[0].y /100
alvr.head_position[2] = freePieIO[0].z /100

diagnostics.watch(alvr.input_head_position[0])
diagnostics.watch(alvr.input_head_position[1])
diagnostics.watch(alvr.input_head_position[2])  
diagnostics.watch(alvr.head_position[0])
diagnostics.watch(alvr.head_position[1])
diagnostics.watch(alvr.head_position[2])

but it seems to have no effect. I tried to exaggerate the values to make the changes appear more obvious, but still no luck, so no doubt, the syntax is wrong. I'm confused about whether alvr.head_position already incorporates the offset or not. In other words,  does "alvr.head_position[0] = alvr.input_head_position[0] + offset[0]" need to be specified, or is it always the case? if it is implicit, than just specifying some offset values at the top of the script would be enough. Any wisdom thrown in this direction on this matter will be appreciated!

The reason why an offset is need is in the first place is because the tracker sits on the top-center of my head (on the top strap) while the system probably assumes its position to be where my eyes are. So when looking down, the position shifts forward.

So, how do you correctly apply an offset?

Cheers!

**Comment by polygraphene** [comment] 2018-06-30 11:03
```
alvr.head_position[0] = alvr.input_head_position[0] + offset[0]
alvr.head_position[1] = alvr.input_head_position[1] + offset[1]
alvr.head_position[2] = alvr.input_head_position[2] + offset[2]
alvr.head_position[0] = freePieIO[0].x /100
alvr.head_position[1] = freePieIO[0].y /100
alvr.head_position[2] = freePieIO[0].z /100
```
You overridden head_position.

This may work.
```
alvr.head_position[0] = alvr.input_head_position[0] + offset[0] + freePieIO[0].x /100
alvr.head_position[1] = alvr.input_head_position[1] + offset[1] + freePieIO[0].y /100
alvr.head_position[2] = alvr.input_head_position[2] + offset[2] + freePieIO[0].z /100
```

**Comment by VRtinker** [comment] 2018-06-30 16:01
> What are you using to get positional tracking? Driver4vr?

No, as I said in the first post here, and in #79, I'm using PSMoveSteamVRBridge+PSMoveFreepieBridge.

Now off to figure out this offset ordeal!

**Comment by Lightsteed** [comment] 2018-06-30 18:20
Ah i see.. yes this is going to be a common issue for other drivers interacting with ALVR it seems. I tried using openvr input emulator to change the position of the oculus go hmd when using alvr and it does not work at all. Im thinking it will be best for the albr dev to try and make the software compatible with other such drivers so that they can take more control or position and orientation and not lose any fidelity on the image. It seems to work for vridge, but they do not use ATW, so there are probably challenges to overcome there.

**Comment by VRtinker** [comment] 2018-06-30 18:35
@polygraphene 

Thanks for your pointer!

While your suggestion works (yay!) it does require to declare the offset variable and its value at the beginning of the script, as in:

global offset
if starting:
  offset = [0.0, 0.1, -0.1]
  
alvr.override_head_position = True

alvr.head_position[0] = alvr.input_head_position[0] + offset[0] + freePieIO[0].x /100
alvr.head_position[1] = alvr.input_head_position[1] + offset[1] + freePieIO[0].y /100
alvr.head_position[2] = alvr.input_head_position[2] + offset[2] + freePieIO[0].z /100

#optional, for diagnostic purposes
diagnostics.watch(alvr.input_head_position[0])
diagnostics.watch(alvr.input_head_position[1])
diagnostics.watch(alvr.input_head_position[2])  
diagnostics.watch(alvr.head_position[0])
diagnostics.watch(alvr.head_position[1])
diagnostics.watch(alvr.head_position[2])

I found I can instead use this formula to get the same result without the mouthful :-P

alvr.override_head_position = True

alvr.head_position[0] = freePieIO[0].x /100
alvr.head_position[1] = (freePieIO[0].y /100) + .1
alvr.head_position[2] = (freePieIO[0].z /100) - 0.1

#optional, for diagnostic purpose
diagnostics.watch(alvr.input_head_position[0])
diagnostics.watch(alvr.input_head_position[1])
diagnostics.watch(alvr.input_head_position[2])  
diagnostics.watch(alvr.head_position[0])
diagnostics.watch(alvr.head_position[1])
diagnostics.watch(alvr.head_position[2])

Maybe the first script is cleaner since should you ever need to change the offset's value, you can do it all at once on the declaration line, but on the other hand, it's not like you need to ever change the offset again once you find the correct values, so unless you see an adverse effect when using the second script, I will probably stick with that!

I'm still getting a bit of "bouncy" feeling when looking down, or moving in general, but, for the moment, I'm writing it off to the fact that I'm using only 2 PS3 cam for tracking (it's kinda like a smoothing feel, hard to describe, maybe I'll make a video if you are interested - even though I'm not sure it would even appear evident on a 2D screen) . Since I actually bough 6 of them (for a whooping $11.94 total!), I'll try to hook up one or two more to see if that improves the overall experience.

I'll be back when I gather more data!

@Lightsteed 

Not sure what's the "common issue" you are referring to, but tracking works perfectly fine without using driver4vr. It sure can use some tuning, but at least the method to add an offset is now clear.

**Comment by Peng180** [comment] 2018-10-14 07:34
@VRtinker 

I'm using PSMoveSteamVRBridge and PSMoveFreepieBridge as well, but after running the following script in FreePie I can't get positional tracking in ALVR.I wonder what's the problem.
-------------------------------------------------------------------------------------------
global offset
if starting:
 offset = [0.0, 0.1, -0.1]
alvr.override_head_position = True
alvr.head_position[0] = freePieIO[0].x /100
alvr.head_position[1] = (freePieIO[0].y /100) + .1
alvr.head_position[2] = (freePieIO[0].z /100) - 0.1
#optional, for diagnostic purpose
diagnostics.watch(alvr.input_head_position[0])
diagnostics.watch(alvr.input_head_position[1])
diagnostics.watch(alvr.input_head_position[2])
diagnostics.watch(alvr.head_position[0])
diagnostics.watch(alvr.head_position[1])
diagnostics.watch(alvr.head_position[2])
--------------------------------------------------------------------------------------------
I use LED ping pong ball for head tracking in PSMoveService and it tests good, the software I am using:
PSMoveSteamVRBridge_1.5.0
PSMoveFreepieBridge-Release15
ALVR-portable-v2.3.1

Any help is appreciated.

**Comment by Peng180** [comment] 2018-10-14 14:46
Problem sloved after updating PSMoveFreepieBridge to release 16 by HipsterSloth. Finally got my GO 6dof tracking!

**Closed** 2021-11-08 11:23 UTC
