### ISSUE TITLE
2 log files for 1 crash and 1 freeze.

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#109] opened 2018-06-29 22:39 UTC
This one client crashed while playing beat saber. Had 1.5mb buffer. Lowered to 500kb since then. 
https://1drv.ms/u/s!AghkviLYNl5k0ag4OXqEGBRTRcGHAw

This one froze and the sound started cracking while playing moss.
https://1drv.ms/u/s!AghkviLYNl5k0ag3ZzsvFOGX_DbZVQ

All using normal latest beta version

**Comment by polygraphene** [comment] 2018-06-30 03:33
Thank you for report.

First one.
> 06-30 00:46:07.354 31804 32629 E AndroidRuntime: FATAL EXCEPTION: com.polygraphene.alvr.DecoderThread
06-30 00:46:07.354 31804 32629 E AndroidRuntime: Process: com.polygraphene.alvr, PID: 31804
06-30 00:46:07.354 31804 32629 E AndroidRuntime: java.nio.BufferOverflowException
06-30 00:46:07.354 31804 32629 E AndroidRuntime: 	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:278)
06-30 00:46:07.354 31804 32629 E AndroidRuntime: 	at com.polygraphene.alvr.DecoderThread.sendInputBuffer(DecoderThread.java:314)
06-30 00:46:07.354 31804 32629 E AndroidRuntime: 	at com.polygraphene.alvr.DecoderThread.decodeLoop(DecoderThread.java:269)
06-30 00:46:07.354 31804 32629 E AndroidRuntime: 	at com.polygraphene.alvr.DecoderThread.run(DecoderThread.java:151)
06-30 00:46:07.354 31804 32629 E AndroidRuntime: 	at com.polygraphene.alvr.DecoderThread$MyThread.run(DecoderThread.java:402)

This is caused by small buffer of MediaCodec. I will try to fix by splitting input frame.

The second issue is caused by bad packet losses. Do you get the same issue if you lowering bitrate?
I want to see driver.log on server side.

**Comment by vrokolos** [comment] 2018-06-30 07:50
I need to enable debug logging on server side for the driver.log? I can't find it.

Anyway here's an unrelated crash log on the server: https://1drv.ms/u/s!AghkviLYNl5k0ag5zFvM2IS50_JPrw

**Comment by polygraphene** [comment] 2018-07-09 18:01
First error may be fixed on v2.2.3-alpha.
Please try.
https://github.com/polygraphene/ALVR/releases/tag/v2.2.3-alpha

**Comment by vrokolos** [comment] 2018-07-09 18:44
Well I'll have to try for this during the week since it didn't happen all the time. I tried playing for 5 minutes and it was okish.

**Comment by vrokolos** [comment] 2018-07-09 19:04
Here is a freeze (if I got the log correctly): https://1drv.ms/u/s!AghkviLYNl5k0eJqhdVg4hKG5X_3Og

**Comment by vrokolos** [comment] 2018-07-09 19:23
Played 10 minutes without any freeze/crash by lowering bitrate to 26mbit:
https://1drv.ms/u/s!AghkviLYNl5k0eJrrHIGhFkTIKriAg

**Comment by polygraphene** [comment] 2018-07-10 13:04
Thank you for trying!

>Here is a freeze (if I got the log correctly): https://1drv.ms/u/s!AghkviLYNl5k0eJqhdVg4hKG5X_3Og
...
07-09 22:00:44.193  5325  5735 V FrameTracking: [Frame 41616] Previous frame cannot be recovered....

The log shows continuous packet loss which cannot be recovered by FEC.
I didn't get the exact reason of freeze, but that bitrate may be hard to your network.
The client seemed stop on 22:00:45 according to the log.
Can you see the streaming correctly before that time?

>Played 10 minutes without any freeze/crash by lowering bitrate to 26mbit:
https://1drv.ms/u/s!AghkviLYNl5k0eJrrHIGhFkTIKriAg

This one shows no FEC error.

**Comment by vrokolos** [comment] 2018-07-10 13:06
Yes I gather it's the FEC that freezes the stream. The gameplay was OK even on the high bitrate didn't notice any major broken images. So I bet too many FEC errors freeze the stream.

**Closed** 2021-11-08 11:22 UTC
