### ISSUE TITLE
Stuck on "Press Connect Button" even after starting server

### ISSUE THREAD

**Issue by Adblue** [polygraphene/ALVR#343] opened 2019-05-29 00:21 UTC
When setting ALVR up with SteamVR, everything was going smoothly. When I hit connect and start the server, SteamVR starts up but my Quest is still stuck on that "Press Connect Button" screen and SteamVR seemingly can't detect my headset as I cannot get past Room Setup.

**Comment by Thaurin** [comment] 2019-05-29 00:28
This happened to me as well for a time, before I got my issue #338 with the green screen. I'm not sure what causes it, but I can say for sure that the ALVR server reported connected while the Quest screen was still in the "Press Connect Button" screen.

**Comment by Adblue** [comment] 2019-05-29 00:55
> This happened to me as well for a time, before I got my issue #338 with the green screen. I'm not sure what causes it, but I can say for sure that the ALVR server reported connected while the Quest screen was still in the "Press Connect Button" screen.

Were you able to get things fixed and start playing? If so what steps did you go through?

**Comment by LAP87** [comment] 2019-05-29 04:40
I used Riftcat/Vridge to get past room-setup before i found out about ALVR, and then i installed "OpenVR Advanced Settings", which is a godsend, especially when you need to adjust floor levels in steamvr quickly.

**Comment by SSSTREDDD** [comment] 2019-05-29 12:22
Duplicate of #328

**Comment by Thaurin** [comment] 2019-05-29 13:40
> Were you able to get things fixed and start playing? If so what steps did you go through?

I think my issue was with SteamVR not running correctly. Eventually it just worked after reinstalling/restarting everything.

**Comment by Adblue** [comment] 2019-05-29 22:02
> Duplicate of #328
> 
> I have posted the solution there, hope this helps.

I managed to get it working but only through a mobile hotspot. For some reason my actual wifi connection just will not work. Such a bizarre issue...

**Comment by velteyn** [comment] 2020-03-22 14:14
same here I have this situation:
PC atacched by cable on router,
Headset attacched by wifio on the same router.
I think that udp packets generated by ethernet are lost on wifi for some reason..

**Closed** 2021-11-08 11:05 UTC
