### ISSUE TITLE
can't find my headset

### ISSUE THREAD

**Issue by xjqxzh1** [polygraphene/ALVR#488] opened 2019-08-02 09:45 UTC
I'm trying to find gear vr. The server version is v2.4.0-alpha5 and the client version is 2.3.1.I have created a rule for udp 9944. I find that when i start the server, vrserver.exe won't start and udp port 9943 will be used.I don't know if it is normal.No UDP package from port 9943/9944 can be captured by wireshark. Could you give me some suggestions? Thank you very much!!

**Comment by CodeMonk** [comment] 2019-08-02 23:04
Same - i also ran wireshark and saw all the packets from the phone, but nothing from the alvr server. It did seem to be communicating with something on localhost tcp port 9944, but, I think that's just the steamvr part.

**Comment by krzys-h** [comment] 2019-08-03 21:57
I was debugging the exact same issue some time ago. The store version of the client is v2.3.1 and doesn't seem to be compatible with the later v2.4.0-alpha server versions - either downgrade the server, or build the alpha client as explained in https://github.com/polygraphene/ALVR/blob/master/README.md#alvr-client (it's not possible to simply share the updated file because of some weird Oculus signing stuff)

(also a duplicate of #487)

**Comment by xjqxzh1** [comment] 2019-08-05 00:39
@krzys-h I will downgrade the server and try again. Thank you very much!

**Closed** 2021-11-08 10:53 UTC
